export const CONTRACTS = {
  REWARDS: process.env.NEXT_PUBLIC_REWARDS_CONTRACT,
  NFT: process.env.NEXT_PUBLIC_NFT_CONTRACT,
  TOKEN: process.env.NEXT_PUBLIC_TOKEN_CONTRACT,
  MARKETPLACE: process.env.NEXT_PUBLIC_MARKETPLACE_CONTRACT,
  TREASURY: process.env.NEXT_PUBLIC_TREASURY_CONTRACT
} as const; 